### ISSUE TITLE
css var()不生效问题

### ISSUE THREAD

**Issue by LWD8** [jkchao/blog-front#14]
#我自己重写了一次，想请教一下

###css var()我的没生效？是用了什么插件吗？我看了你的DEMO，找不着   -_-
我的没编译：
![image](https://user-images.githubusercontent.com/28432674/48815309-0bd2f300-ed79-11e8-9b75-c871e8ebc2b8.png)
你的编译：
![image](https://user-images.githubusercontent.com/28432674/48815379-4ccb0780-ed79-11e8-8dad-a34b8bdfe936.png)

**Comment by jkchao** [comment]
网上搜一下，我也忘记了 😃

**Comment by LWD8** [comment]
很尴尬~~昨天找到现在都没找着怎么处理，网上也不知道怎么去搜索。可以给个提示怎么去百度不？

**Comment by LWD8** [comment]
找到了，是mixin新版用法不一样了，变量必须加#{}，才能编译出来

![image](https://user-images.githubusercontent.com/28432674/48930044-a6bdff80-ef28-11e8-902a-a8315ab6f736.png)

浏览器编译：
![image](https://user-images.githubusercontent.com/28432674/48930050-b3425800-ef28-11e8-9a98-3fe05c80835a.png)
